# Informaci贸n
title: Documentaci贸n <dev>
tagline: Documentaci贸n
description: Documentaci贸n para desarrollo full-stack
author: fidelvo

# Acceso
baseurl: "/dev-docs/_site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "README.md"]
# logo: "/assets/img/logo.png"

# Tema
theme: "just-the-docs"
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ''
      type: slides
    values:
      layout: posts
      search_exclude: true
      sitemap: false
